<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1ms677m\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1ms677m/appProdProjectContainer.php') {
    touch(__DIR__.'/Container1ms677m.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container1ms677m\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container1ms677m\appProdProjectContainer(array(
    'container.build_hash' => '1ms677m',
    'container.build_id' => '5d170a01',
    'container.build_time' => 1541793734,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1ms677m');
