<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQfi5dcx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQfi5dcx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQfi5dcx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQfi5dcx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQfi5dcx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Qfi5dcx',
    'container.build_id' => 'bf7f27b6',
    'container.build_time' => 1541691598,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQfi5dcx');
